"""updated table number to inclde text

Revision ID: 93b588025df5
Revises: 
Create Date: 2019-04-29 14:17:52.052280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b588025df5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'table', ['number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table', type_='unique')
    # ### end Alembic commands ###
