"""erros all the way

Revision ID: e2505eb05ec0
Revises: 6982ff58959b
Create Date: 2019-04-30 11:36:43.435556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2505eb05ec0'
down_revision = '6982ff58959b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request', 'table_number',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('request', 'time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.create_unique_constraint(None, 'request', ['table_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='unique')
    op.alter_column('request', 'time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('request', 'table_number',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
